// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/mangahubv1/mangahub.proto

package mangahubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MangaHubService_SearchManga_FullMethodName    = "/mangahub.v1.MangaHubService/SearchManga"
	MangaHubService_GetManga_FullMethodName       = "/mangahub.v1.MangaHubService/GetManga"
	MangaHubService_UpdateProgress_FullMethodName = "/mangahub.v1.MangaHubService/UpdateProgress"
)

// MangaHubServiceClient is the client API for MangaHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MangaHubService exposes gRPC endpoints for manga browsing and reading progress.
type MangaHubServiceClient interface {
	SearchManga(ctx context.Context, in *SearchMangaRequest, opts ...grpc.CallOption) (*SearchMangaResponse, error)
	GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*GetMangaResponse, error)
	// UpdateProgress requires an Authorization metadata header: "Bearer <JWT>".
	UpdateProgress(ctx context.Context, in *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error)
}

type mangaHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMangaHubServiceClient(cc grpc.ClientConnInterface) MangaHubServiceClient {
	return &mangaHubServiceClient{cc}
}

func (c *mangaHubServiceClient) SearchManga(ctx context.Context, in *SearchMangaRequest, opts ...grpc.CallOption) (*SearchMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMangaResponse)
	err := c.cc.Invoke(ctx, MangaHubService_SearchManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaHubServiceClient) GetManga(ctx context.Context, in *GetMangaRequest, opts ...grpc.CallOption) (*GetMangaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMangaResponse)
	err := c.cc.Invoke(ctx, MangaHubService_GetManga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mangaHubServiceClient) UpdateProgress(ctx context.Context, in *UpdateProgressRequest, opts ...grpc.CallOption) (*UpdateProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProgressResponse)
	err := c.cc.Invoke(ctx, MangaHubService_UpdateProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MangaHubServiceServer is the server API for MangaHubService service.
// All implementations must embed UnimplementedMangaHubServiceServer
// for forward compatibility.
//
// MangaHubService exposes gRPC endpoints for manga browsing and reading progress.
type MangaHubServiceServer interface {
	SearchManga(context.Context, *SearchMangaRequest) (*SearchMangaResponse, error)
	GetManga(context.Context, *GetMangaRequest) (*GetMangaResponse, error)
	// UpdateProgress requires an Authorization metadata header: "Bearer <JWT>".
	UpdateProgress(context.Context, *UpdateProgressRequest) (*UpdateProgressResponse, error)
	mustEmbedUnimplementedMangaHubServiceServer()
}

// UnimplementedMangaHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMangaHubServiceServer struct{}

func (UnimplementedMangaHubServiceServer) SearchManga(context.Context, *SearchMangaRequest) (*SearchMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchManga not implemented")
}
func (UnimplementedMangaHubServiceServer) GetManga(context.Context, *GetMangaRequest) (*GetMangaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManga not implemented")
}
func (UnimplementedMangaHubServiceServer) UpdateProgress(context.Context, *UpdateProgressRequest) (*UpdateProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgress not implemented")
}
func (UnimplementedMangaHubServiceServer) mustEmbedUnimplementedMangaHubServiceServer() {}
func (UnimplementedMangaHubServiceServer) testEmbeddedByValue()                         {}

// UnsafeMangaHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MangaHubServiceServer will
// result in compilation errors.
type UnsafeMangaHubServiceServer interface {
	mustEmbedUnimplementedMangaHubServiceServer()
}

func RegisterMangaHubServiceServer(s grpc.ServiceRegistrar, srv MangaHubServiceServer) {
	// If the following call panics, it indicates UnimplementedMangaHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MangaHubService_ServiceDesc, srv)
}

func _MangaHubService_SearchManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaHubServiceServer).SearchManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaHubService_SearchManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaHubServiceServer).SearchManga(ctx, req.(*SearchMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaHubService_GetManga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMangaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaHubServiceServer).GetManga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaHubService_GetManga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaHubServiceServer).GetManga(ctx, req.(*GetMangaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MangaHubService_UpdateProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MangaHubServiceServer).UpdateProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MangaHubService_UpdateProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MangaHubServiceServer).UpdateProgress(ctx, req.(*UpdateProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MangaHubService_ServiceDesc is the grpc.ServiceDesc for MangaHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MangaHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mangahub.v1.MangaHubService",
	HandlerType: (*MangaHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchManga",
			Handler:    _MangaHubService_SearchManga_Handler,
		},
		{
			MethodName: "GetManga",
			Handler:    _MangaHubService_GetManga_Handler,
		},
		{
			MethodName: "UpdateProgress",
			Handler:    _MangaHubService_UpdateProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mangahubv1/mangahub.proto",
}
