// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/mangahubv1/mangahub.proto

package mangahubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        string                 `protobuf:"bytes,4,opt,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SearchMangaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If empty, returns all manga.
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaRequest) Reset() {
	*x = SearchMangaRequest{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaRequest) ProtoMessage() {}

func (x *SearchMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaRequest.ProtoReflect.Descriptor instead.
func (*SearchMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMangaRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*Manga               `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMangaResponse) Reset() {
	*x = SearchMangaResponse{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMangaResponse) ProtoMessage() {}

func (x *SearchMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMangaResponse.ProtoReflect.Descriptor instead.
func (*SearchMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMangaResponse) GetMangas() []*Manga {
	if x != nil {
		return x.Mangas
	}
	return nil
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{3}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaResponse) Reset() {
	*x = GetMangaResponse{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaResponse) ProtoMessage() {}

func (x *GetMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaResponse.ProtoReflect.Descriptor instead.
func (*GetMangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{4}
}

func (x *GetMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *UpdateProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type UpdateProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressResponse) Reset() {
	*x = UpdateProgressResponse{}
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressResponse) ProtoMessage() {}

func (x *UpdateProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mangahubv1_mangahub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressResponse.ProtoReflect.Descriptor instead.
func (*UpdateProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_mangahubv1_mangahub_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_mangahubv1_mangahub_proto protoreflect.FileDescriptor

const file_proto_mangahubv1_mangahub_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/mangahubv1/mangahub.proto\x12\vmangahub.v1\"\xbe\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x01(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"*\n" +
	"\x12SearchMangaRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"A\n" +
	"\x13SearchMangaResponse\x12*\n" +
	"\x06mangas\x18\x01 \x03(\v2\x12.mangahub.v1.MangaR\x06mangas\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10GetMangaResponse\x12(\n" +
	"\x05manga\x18\x01 \x01(\v2\x12.mangahub.v1.MangaR\x05manga\"L\n" +
	"\x15UpdateProgressRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x02 \x01(\x05R\achapter\"2\n" +
	"\x16UpdateProgressResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x87\x02\n" +
	"\x0fMangaHubService\x12P\n" +
	"\vSearchManga\x12\x1f.mangahub.v1.SearchMangaRequest\x1a .mangahub.v1.SearchMangaResponse\x12G\n" +
	"\bGetManga\x12\x1c.mangahub.v1.GetMangaRequest\x1a\x1d.mangahub.v1.GetMangaResponse\x12Y\n" +
	"\x0eUpdateProgress\x12\".mangahub.v1.UpdateProgressRequest\x1a#.mangahub.v1.UpdateProgressResponseB&Z$mangahub/proto/mangahubv1;mangahubv1b\x06proto3"

var (
	file_proto_mangahubv1_mangahub_proto_rawDescOnce sync.Once
	file_proto_mangahubv1_mangahub_proto_rawDescData []byte
)

func file_proto_mangahubv1_mangahub_proto_rawDescGZIP() []byte {
	file_proto_mangahubv1_mangahub_proto_rawDescOnce.Do(func() {
		file_proto_mangahubv1_mangahub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mangahubv1_mangahub_proto_rawDesc), len(file_proto_mangahubv1_mangahub_proto_rawDesc)))
	})
	return file_proto_mangahubv1_mangahub_proto_rawDescData
}

var file_proto_mangahubv1_mangahub_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_mangahubv1_mangahub_proto_goTypes = []any{
	(*Manga)(nil),                  // 0: mangahub.v1.Manga
	(*SearchMangaRequest)(nil),     // 1: mangahub.v1.SearchMangaRequest
	(*SearchMangaResponse)(nil),    // 2: mangahub.v1.SearchMangaResponse
	(*GetMangaRequest)(nil),        // 3: mangahub.v1.GetMangaRequest
	(*GetMangaResponse)(nil),       // 4: mangahub.v1.GetMangaResponse
	(*UpdateProgressRequest)(nil),  // 5: mangahub.v1.UpdateProgressRequest
	(*UpdateProgressResponse)(nil), // 6: mangahub.v1.UpdateProgressResponse
}
var file_proto_mangahubv1_mangahub_proto_depIdxs = []int32{
	0, // 0: mangahub.v1.SearchMangaResponse.mangas:type_name -> mangahub.v1.Manga
	0, // 1: mangahub.v1.GetMangaResponse.manga:type_name -> mangahub.v1.Manga
	1, // 2: mangahub.v1.MangaHubService.SearchManga:input_type -> mangahub.v1.SearchMangaRequest
	3, // 3: mangahub.v1.MangaHubService.GetManga:input_type -> mangahub.v1.GetMangaRequest
	5, // 4: mangahub.v1.MangaHubService.UpdateProgress:input_type -> mangahub.v1.UpdateProgressRequest
	2, // 5: mangahub.v1.MangaHubService.SearchManga:output_type -> mangahub.v1.SearchMangaResponse
	4, // 6: mangahub.v1.MangaHubService.GetManga:output_type -> mangahub.v1.GetMangaResponse
	6, // 7: mangahub.v1.MangaHubService.UpdateProgress:output_type -> mangahub.v1.UpdateProgressResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mangahubv1_mangahub_proto_init() }
func file_proto_mangahubv1_mangahub_proto_init() {
	if File_proto_mangahubv1_mangahub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mangahubv1_mangahub_proto_rawDesc), len(file_proto_mangahubv1_mangahub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mangahubv1_mangahub_proto_goTypes,
		DependencyIndexes: file_proto_mangahubv1_mangahub_proto_depIdxs,
		MessageInfos:      file_proto_mangahubv1_mangahub_proto_msgTypes,
	}.Build()
	File_proto_mangahubv1_mangahub_proto = out.File
	file_proto_mangahubv1_mangahub_proto_goTypes = nil
	file_proto_mangahubv1_mangahub_proto_depIdxs = nil
}
