-- MangaHub seed dataset
-- Idempotent: safe to run multiple times.

INSERT OR IGNORE INTO manga (id, title, author, genres, status, total_chapters, description) VALUES
('one-piece','One Piece','Eiichiro Oda','Action,Adventure,Comedy','Ongoing',1100,'A pirate crew searches for the legendary treasure One Piece.'),
('naruto','Naruto','Masashi Kishimoto','Action,Adventure,Ninja','Completed',700,'A young ninja works to earn recognition and become the Hokage.'),
('bleach','Bleach','Tite Kubo','Action,Supernatural','Completed',686,'A teen gains Soul Reaper powers and battles spirits and enemies.'),
('dragon-ball','Dragon Ball','Akira Toriyama','Action,Adventure,Martial Arts','Completed',519,'Goku journeys through epic battles while searching for Dragon Balls.'),
('attack-on-titan','Attack on Titan','Hajime Isayama','Action,Dark Fantasy','Completed',139,'Humanity fights for survival behind walls against giant Titans.'),
('fullmetal-alchemist','Fullmetal Alchemist','Hiromu Arakawa','Action,Adventure,Fantasy','Completed',108,'Two brothers use alchemy to recover what they lost and uncover a conspiracy.'),
('death-note','Death Note','Tsugumi Ohba','Mystery,Psychological,Thriller','Completed',108,'A notebook grants the power to kill, sparking a battle of wits with a detective.'),
('demon-slayer','Demon Slayer: Kimetsu no Yaiba','Koyoharu Gotouge','Action,Dark Fantasy','Completed',205,'A boy joins demon slayers to cure his sister and defeat demons.'),
('jujutsu-kaisen','Jujutsu Kaisen','Gege Akutami','Action,Supernatural','Ongoing',270,'A student enters a world of curses and sorcerers after a fateful encounter.'),
('my-hero-academia','My Hero Academia','Kohei Horikoshi','Action,Superhero','Completed',430,'A powerless boy inherits a hero power and trains to become the greatest hero.'),
('hunter-x-hunter','Hunter x Hunter','Yoshihiro Togashi','Action,Adventure','Ongoing',410,'A boy becomes a Hunter to find his father and faces dangerous trials.'),
('berserk','Berserk','Kentaro Miura','Action,Dark Fantasy','Ongoing',380,'A lone swordsman struggles through a brutal world of war and monsters.'),
('vinland-saga','Vinland Saga','Makoto Yukimura','Action,Historical','Ongoing',215,'A Viking warrior seeks purpose and peace after a life of revenge.'),
('chainsaw-man','Chainsaw Man','Tatsuki Fujimoto','Action,Dark Fantasy','Ongoing',180,'A debt-ridden teen merges with a devil and fights in a chaotic world.'),
('spy-x-family','SPY x FAMILY','Tatsuya Endo','Action,Comedy,Slice of Life','Ongoing',120,'A spy builds a fake family for a mission, unaware of their secrets.'),
('one-punch-man','One-Punch Man','ONE','Action,Comedy,Superhero','Ongoing',200,'A hero defeats enemies with one punch and searches for a real challenge.'),
('tokyo-ghoul','Tokyo Ghoul','Sui Ishida','Action,Horror,Supernatural','Completed',143,'A student becomes half-ghoul and navigates a hidden world of predators.'),
('fairy-tail','Fairy Tail','Hiro Mashima','Action,Adventure,Fantasy','Completed',545,'Wizards in a guild take on quests and face dark forces together.'),
('black-clover','Black Clover','Yuki Tabata','Action,Fantasy','Ongoing',380,'A magicless boy aims to become Wizard King through grit and teamwork.'),
('haikyuu','Haikyu!!','Haruichi Furudate','Sports,Comedy','Completed',402,'A short volleyball player chases greatness with his high school team.'),
('dr-stone','Dr. Stone','Riichiro Inagaki','Adventure,Sci-Fi','Completed',232,'After humanity turns to stone, a genius rebuilds civilization with science.'),
('jojo-bizarre-adventure','JoJo''s Bizarre Adventure','Hirohiko Araki','Action,Adventure,Supernatural','Ongoing',1000,'Generations of the Joestar family battle supernatural foes across eras.'),
('kaguya-sama','Kaguya-sama: Love Is War','Aka Akasaka','Comedy,Romance','Completed',281,'Two elite students play mind games to make the other confess first.'),
('fruits-basket','Fruits Basket','Natsuki Takaya','Drama,Romance,Slice of Life','Completed',136,'A girl befriends a cursed family and helps them heal and change.'),
('slam-dunk','Slam Dunk','Takehiko Inoue','Sports,Comedy','Completed',276,'A delinquent joins a basketball team and discovers discipline and passion.'),
('vagabond','Vagabond','Takehiko Inoue','Action,Historical','Ongoing',327,'A retelling of Miyamoto Musashi and the path of the sword.'),
('monster','Monster','Naoki Urasawa','Mystery,Thriller','Completed',162,'A doctor hunts a serial killer he once saved, unraveling a dark mystery.'),
('twentieth-century-boys','20th Century Boys','Naoki Urasawa','Mystery,Sci-Fi,Thriller','Completed',249,'Childhood memories become real as friends face a global conspiracy.'),
('gintama','Gintama','Hideaki Sorachi','Action,Comedy,Sci-Fi','Completed',704,'A samurai and friends take odd jobs in an alien-ruled Edo.'),
('the-promised-neverland','The Promised Neverland','Kaiu Shirai','Mystery,Thriller','Completed',181,'Orphans discover a terrifying truth and plan a desperate escape.'),
('tokyo-revengers','Tokyo Revengers','Ken Wakui','Action,Drama,Time Travel','Completed',278,'A man travels back in time to save friends and change a gang-driven future.'),
('blue-lock','Blue Lock','Muneyuki Kaneshiro','Sports,Drama','Ongoing',300,'Strikers compete in an intense program to create Japans best soccer forward.'),
('mob-psycho-100','Mob Psycho 100','ONE','Comedy,Supernatural,Action','Completed',101,'A mild teen with psychic powers learns to grow and control his emotions.'),
('made-in-abyss','Made in Abyss','Akihito Tsukushi','Adventure,Fantasy','Ongoing',70,'A girl descends into a vast abyss filled with wonders and dangers.'),
('claymore','Claymore','Norihiro Yagi','Action,Dark Fantasy','Completed',155,'Warrior women hunt monsters while fighting the darkness within.'),
('akira','Akira','Katsuhiro Otomo','Action,Sci-Fi','Completed',120,'In Neo-Tokyo, psychic power threatens society and two friends collide.'),
('uzumaki','Uzumaki','Junji Ito','Horror,Psychological','Completed',20,'A small town becomes obsessed with spirals, spiraling into madness.'),
('tokyo-esp','Tokyo ESP','Hajime Segawa','Action,Supernatural','Completed',76,'A girl gains psychic powers and gets pulled into a citywide conflict.'),
('assassination-classroom','Assassination Classroom','Yusei Matsui','Action,Comedy','Completed',180,'Students train to assassinate their strange teacher to save the world.'),
('tokyo-mew-mew','Tokyo Mew Mew','Reiko Yoshida','Magical Girl,Romance','Completed',32,'Teen girls gain powers to protect Earth from alien threats.'),
('your-lie-in-april','Your Lie in April','Naoshi Arakawa','Drama,Romance,Music','Completed',44,'A pianist rediscovers music through a free-spirited violinist.'),
('erased','ERASED','Kei Sanbe','Mystery,Thriller,Time Travel','Completed',49,'A man relives the past to stop a crime and protect children.'),
('re-life','ReLIFE','Yayoi Sou','Drama,Romance,Slice of Life','Completed',222,'A struggling adult gets a chance to redo high school for one year.'),
('orange','Orange','Ichigo Takano','Drama,Romance','Completed',39,'A girl receives letters from her future self and tries to change regrets.'),
('parasyte','Parasyte','Hitoshi Iwaaki','Action,Horror,Sci-Fi','Completed',64,'Alien parasites invade human bodies and a teen fights for survival.'),
('kingdom','Kingdom','Yasuhisa Hara','Action,Historical,Military','Ongoing',800,'An orphaned boy rises as a general during Chinas Warring States period.'),
('golden-kamuy','Golden Kamuy','Satoru Noda','Adventure,Historical','Completed',314,'A veteran and an Ainu girl hunt for hidden gold across the wild north.'),
('promised-cinderella','Promise Cinderella','Oreco Tachibana','Drama,Romance','Completed',110,'A woman rebuilds her life after hardship and finds unexpected support.');
